version: "3.8"
services:
  frontend:
    image: node:20-slim
    working_dir: /src/frontend
    command: >
      sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    volumes:
      - ./frontend:/src/frontend
      - frontend_node_modules:/src/frontend/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:8000
    tty: true

  backend:
    build:                               # ← ここを image の代わりに使う
      context: .                         # リポジトリのルート
      dockerfile: docker/backend/Dockerfile
    working_dir: /app
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app                   # ソースをマウント（フォントはイメージ側にあるのでOK）
    ports:
      - "8000:8000"
    environment:
      - ADMIN_PASSWORD=1234
      - MPLBACKEND=Agg                   # 念のため

volumes:
  frontend_node_modules: